[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests", "ls -la target/*.jar"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=mysql -jar $(ls target/*.jar | grep -v original | head -1)"
